-- SatıcıPilot — Lead Round 13 (14 lead)
-- Odak: Niş değil, yüksek potansiyel müşteri profili
-- Seçim kriterleri: yüksek yorum hacmi · çok platform · büyüyen ekip · net otomasyon ihtiyacı

INSERT INTO leads (shop_name, marketplace, contact_name, contact_email, contact_phone, store_url, status, source, notes) VALUES

-- ── BÜYÜYEN DTC & MULTI-PLATFORM ────────────────────────────────
('Farmasi', 'trendyol', NULL, 'musteri@farmasi.com.tr', '08503260505', 'https://www.trendyol.com/farmasi-x-b345', 'kesfedildi', 'instagram', 'Niche: cilt bakım + makyaj + saç bakım + parfüm · 2004 kuruluş, DTC + doğrudan satış hybrid model · Trendyol + HB + kendi platform + distribütör ağı · Binlerce micro-influencer iş birliği → kampanya sonrası yorum patlamaları yönetilemiyor · Çok kanal = farklı platformda yorum takibi manuel → SatıcıPilot unified dashboard tek başına büyük ROI · Büyüme fazında ekip kapasitesi yetersiz kalıyor'),
('Anker Türkiye', 'trendyol', NULL, 'support@anker.com.tr', NULL, 'https://www.trendyol.com/anker-x-b2341', 'kesfedildi', 'website', 'Niche: powerbank + USB-C kablo + hızlı şarj başlığı + TWS kulaklık + hoparlör · Global tech aksesuar devinin Türkiye kanalı · Trendyol + Amazon.com.tr + HB üç platform eş zamanlı · Teknik yorum çok detaylı gelir (şarj hızı, uyumluluk, ısınma) → kategori bazlı şablon yanıt kritik · DOA & garanti iade süreci yoğun → iade takip modülü operasyonel zorunluluk · Haftalık yeni ürün lansmanı = sürekli açıklama güncelleme ihtiyacı'),

-- ── KADIN MODA — YÜKSEK YORUm HACMİ & İADE BASKISI ────────────
('Penti', 'trendyol', NULL, 'musteri@penti.com.tr', '08503020022', 'https://www.trendyol.com/penti-x-b456', 'kesfedildi', 'instagram', 'Niche: çorap + külotlu çorap + iç çamaşırı + pijama + ev giyim · Türkiye''nin lider çorap & iç giyim zinciri, 150+ mağaza · Trendyol + HB + D2C · Sezon geçişinde 100+ yeni SKU aynı anda listeye girer → açıklama & tag optimizasyonu manuel tutmak imkânsız · Renk/beden uyumsuzluğu iade oranı yüksek → SatıcıPilot iade analizi kalıp tespiti somut ROI · Çok platform eş zamanlı yorum yükü ağır'),
('Roman', 'trendyol', NULL, 'musteri@roman.com.tr', '08508502030', 'https://www.trendyol.com/roman-x-b567', 'kesfedildi', 'website', 'Niche: kadın & erkek giyim, casual + formal + dış giyim · Türkiye''nin yaygın moda zincirlerinden, 150+ mağaza · Trendyol + HB + D2C · Büyük indirim kampanyaları döneminde (Black Friday, sezon sonu) sipariş & yorum patlaması → SatıcıPilot kampanya otomasyon + yorum yönetimi zirve dönemde kritik · Geniş yaş segmenti = farklı müşteri profili → yorum tonu analizi değer katar'),
('Twist', 'trendyol', NULL, 'musteri@twist.com.tr', '08504006954', 'https://www.trendyol.com/twist-x-b678', 'kesfedildi', 'instagram', 'Niche: kadın casual giyim · triko + elbise + bluz + pantolon + eşofman · Point Group bünyesi (Network & Machka ile aynı grup) · 100+ mağaza, Trendyol + HB + D2C · Instagram koleksiyonu kampanyaları → sipariş dalgası ani geliyor · Grup içinde üç marka = tek ekibin üç Trendyol mağazasını yönetmesi → SatıcıPilot merkezi panel grup için çok güçlü değer önerisi'),
('İpekyol', 'trendyol', NULL, 'musteri@ipekyol.com.tr', '08502002030', 'https://www.trendyol.com/ipekyol-x-b789', 'kesfedildi', 'instagram', 'Niche: premium ipekli elbise + eşarp + bluz + ceket + aksesuar · 100+ mağaza, 30+ yıllık premium Türk kadın moda markası · Trendyol + HB + D2C + travel retail · 500-5.000 TL ürün aralığı → her olumsuz yorum gelir kaybı büyük · Premium segment müşterisi hızlı yanıt bekler, yanıtsız yorum marka itibarını zedeler → SatıcıPilot yorum izleme alarm sistemi kritik'),
('Sante', 'trendyol', NULL, 'info@sante.com.tr', NULL, 'https://www.trendyol.com/sante-x-b890', 'kesfedildi', 'instagram', 'Niche: kadın topuklu + stiletto + sandalet + düz ayakkabı · 50+ mağaza, Trendyol + HB + D2C · Numara uyumsuzluğu iade oranı ayakkabıda kategorik yüksek → SatıcıPilot iade analizi ile hangi modelde sorun olduğunu tespit etmek net ROI · Sezon geçişinde 80+ yeni model girilmesi = açıklama & fotoğraf iyileştirme iş yükü yoğun'),

-- ── MAKYAJ & KOZMETİK — HAL TETİKLİ YORUM DALGALARI ───────────
('Flormar', 'trendyol', NULL, 'tuketici@flormar.com.tr', '08503400300', 'https://www.trendyol.com/flormar-x-b123', 'kesfedildi', 'instagram', 'Niche: ruj + fondöten + far + maskara + göz kalemi + cilt bakım · 1962 kuruluş, Türkiye''nin en büyük makyaj markalarından · Trendyol + HB + kendi mağaza · 1.000+ SKU, her sezonda yeni koleksiyon → ürün açıklaması & tag optimizasyonu ölçeklenemez · Renk ton yorumları (cilt eşleşmesi, pigmentasyon) çok detaylı gelir → yorum kategorize etme & şablon yanıt büyük verimlilik · Influencer viral dalgası sonrası satış+yorum patlaması'),

-- ── ERKEK MODA & KURUMSAL SEGMENT ───────────────────────────────
('Collezione', 'trendyol', NULL, 'musteri@collezione.com.tr', '08505200200', 'https://www.trendyol.com/collezione-x-b234', 'kesfedildi', 'instagram', 'Niche: erkek takım elbise + slim fit gömlek + ceket + kravat · 50+ mağaza, Trendyol + HB · Düğün, mezuniyet, iş görüşmesi müşterisi = özel gün siparişi yoğun · Beden uyumsuzluğu iade oranı takımda yüksek → SatıcıPilot iade analizi hangi ölçü tablosunun sorunlu olduğunu gösterir · Yüksek bilet ürün = olumsuz yorumun satış etkisi büyük → hızlı yanıt şart'),
('Altınyıldız Classics', 'trendyol', NULL, 'musteri@altinyildiz.com.tr', '08502302020', 'https://www.trendyol.com/altinyildiz-classics-x-b345', 'kesfedildi', 'instagram', 'Niche: erkek takım elbise + gömlek + kravat + kazak + ceket · Türkiye''nin köklü erkek moda gruplarından · 200+ satış noktası, Trendyol + HB + D2C · Kurumsal & düğün müşterisi = kalite beklentisi yüksek, yorum detaylı · Çok kanal sipariş yönetimi yükü büyük → SatıcıPilot merkezi panel operasyonel değer · Sezon lansmanı = yüzlerce yeni SKU eş zamanlı'),
('Damat', 'trendyol', NULL, 'musteri@damat.com.tr', '08503282020', 'https://www.trendyol.com/damat-x-b456', 'kesfedildi', 'instagram', 'Niche: premium erkek takım elbise + gömlek + casual + aksesuar · Türkiye''nin lider premium erkek moda markası, 200+ mağaza · Trendyol + HB + D2C + yurt dışı retail · Düğün sezonu (Mayıs-Eylül) siparişlerde patlama → SatıcıPilot kampanya & stok yönetimi yüksek mevsimsellik · Premium müşteri yanıtsız yorum görünce rakibe geçer → SatıcıPilot yorum alarm sistemi marka için kritik'),
('Pierre Cardin Türkiye', 'trendyol', NULL, 'info@pierrecardin.com.tr', '02163837373', 'https://www.trendyol.com/pierre-cardin-x-b567', 'kesfedildi', 'website', 'Niche: erkek gömlek + pantolon + ceket + kravat + cüzdan + aksesuar · Uluslararası lisanslı marka, Türkiye operasyonu yerel firma · Trendyol + HB + 100+ satış noktası · Çok ürün kategorisi (giyim + aksesuar) = her kategoride farklı yorum tipi → SatıcıPilot çapraz kategori yorum analizi güçlü use-case · Kurumsal hediye segmenti yoğun → kampanya hatırlatma & sipariş takip değerli'),

-- ── CASUAL & ÇOK KANAL — GRUP YÖNETİM İHTİYACI ─────────────────
('Network', 'trendyol', NULL, 'musteri@network.com.tr', '08504006954', 'https://www.trendyol.com/network-x-b678', 'kesfedildi', 'instagram', 'Niche: erkek & kadın casual giyim + triko + dış giyim · Point Group bünyesi (Twist & Machka ile aynı grup) · 150+ mağaza, Trendyol + HB + D2C · Aynı dijital ekip üç Trendyol mağazasını yönetiyor (Network + Twist + Machka) → SatıcıPilot tek panelde çok mağaza yönetimi bu grup için güçlü satış argümanı · Grup bazında tek abonelikle üç marka çözülür → ACV potansiyeli yüksek'),
('Machka', 'trendyol', NULL, 'musteri@machka.com.tr', '08504006954', 'https://www.trendyol.com/machka-x-b789', 'kesfedildi', 'instagram', 'Niche: premium kadın giyim + blazer + etek + pantolon + gece kıyafeti · Point Group''un premium kolu, 80+ mağaza · Trendyol + HB + D2C · Premium segment → yorum kalitesi conversion''u doğrudan etkiler, yanıtsız yorum rakibe kaçış · Büyüme fazında operasyon ekibi yetersiz → SatıcıPilot ile yorum & iade yönetimi otomasyonu tam fit · Üç markalı grup senaryosunda (Network+Twist+Machka) SatıcıPilot ACV üç kata çıkar')

;
