-- SatıcıPilot — Lead Round 15 (14 lead)
-- Odak: Yüksek potansiyel profil — Vol 14'ün devamı
-- Segmentler: Teknoloji & Ses, Uluslararası Spor Markaları, Lüks & Premium Türk,
-- Premium Evcil Hayvan, Medikal & Sağlık Teknolojisi, Valiz, Bebek, Moda Saat

INSERT INTO leads (shop_name, marketplace, contact_name, contact_email, contact_phone, store_url, status, source, notes) VALUES

-- ── TEKNOLOJİ & SES SİSTEMLERİ ──────────────────────────────────
('Xiaomi Türkiye', 'trendyol', NULL, 'support@xiaomi-turkey.com', NULL, 'https://www.trendyol.com/xiaomi-x-b1234', 'kesfedildi', 'website', 'Niche: akıllı telefon + tablet + TWS kulaklık + akıllı saat + scooter + akıllı ev cihazları · Xiaomi''nin Türkiye yetkili kanalı · Trendyol + Amazon.com.tr + HB üç platform eş zamanlı · 50+ kategoride ürün = her kategori farklı yorum tipi (yazılım hatası, şarj sorunu, uyumluluk) · Yeni model lansmanında yorum patlaması → SatıcıPilot model bazlı yorum kategorize yönetimi · DOA & garanti iade süreci yoğun → iade takip modülü operasyonel zorunluluk · SKU matrisi sürekli genişliyor'),
('JBL Türkiye', 'trendyol', NULL, 'info@jbl.com.tr', NULL, 'https://www.trendyol.com/jbl-x-b2345', 'kesfedildi', 'website', 'Niche: TWS kulaklık + bluetooth hoparlör + soundbar + kulak içi + over-ear · Harman/Samsung iştiraki, Türkiye yetkili distribütörü · Trendyol + HB + Teknosa & MediaMarkt · Teknik ses kalitesi yorumları çok detaylı gelir (bas, netlik, gecikme, eşleşme sorunu) → SatıcıPilot teknik şablon yanıt destek yükünü dramatik azaltır · DOA & garanti iade oranı elektronikte yapısal yüksek · Ürün uyumluluk soruları (iOS/Android) yoğun'),

-- ── ULUSLARARASI SPOR MARKALARI — TÜRK OPERASYON, GLOBAL BASINÇ ─
('Puma Türkiye', 'trendyol', NULL, 'musteri@puma.com.tr', NULL, 'https://www.trendyol.com/puma-x-b3456', 'kesfedildi', 'instagram', 'Niche: spor ayakkabı + activewear + futbol ekipmanı + sporlife aksesuar · Global spor markasının Türkiye yetkili kanalı · Trendyol + HB + FLO ağı + kendi mağazalar · Numara & beden uyumsuzluğu iade oranı spor kategorisinde yapısal yüksek → SatıcıPilot iade analizi · Futbol sezon lansmanları + Efsane Günü''nde yorum patlaması · Global marka algısı → olumsuz yorum brand itibarına direkt etki'),
('New Balance Türkiye', 'trendyol', NULL, 'info@newbalance.com.tr', NULL, 'https://www.trendyol.com/new-balance-x-b4567', 'kesfedildi', 'instagram', 'Niche: premium koşu + yürüyüş + lifestyle sneaker · Premium spor markası, Türkiye''de hızlı büyüme fazında · Trendyol + HB + kendi mağaza · Ortopedik & günlük konfor yorumları detaylı gelir → SatıcıPilot yorum analizi satış artışına katkı · Premium segment müşteri hızlı yanıt bekler · Running kültürünün büyümesiyle birlikte Türkiye pazarında yorum hacmi hızla artıyor'),
('Under Armour Türkiye', 'trendyol', NULL, 'info@underarmour.com.tr', NULL, 'https://www.trendyol.com/under-armour-x-b5678', 'kesfedildi', 'instagram', 'Niche: performans sporwear + sıkıştırma giyim + koşu + antrenman ayakkabısı · Amerikan performans markası, Türkiye yetkili kanalı · Trendyol + HB + spor mağazaları · Teknik performans iddiaları (nem atma, vücut ısısı regülasyonu) yorumlarda test edilir → SatıcıPilot teknik yorum kategorize & hızlı yanıt · Premium segment + sporcu kitlesi = detaylı yorum & yüksek beklenti'),
('Skechers Türkiye', 'trendyol', NULL, 'musteri@skechers.com.tr', '08502002020', 'https://www.trendyol.com/skechers-x-b6789', 'kesfedildi', 'instagram', 'Niche: konfor ayakkabı + memory foam + yürüyüş + günlük + çocuk · Türkiye''de hızlı büyüyen Amerikan konfor ayakkabı markası · 50+ mağaza, Trendyol + HB + D2C · Ortopedik & konfor iddiaları yorumlarda beklenti oluşturur → SatıcıPilot yorum analizi beklenti-gerçeklik açığını tespit eder · Numara uyumsuzluğu iade oranı yüksek → iade kalıp analizi somut ROI · Yaşlı & sağlık odaklı müşteri segmenti yorum yazma oranı yüksek'),

-- ── LÜKS & PREMİUM TÜRK MARKA — HER YORUM MARKA DEĞERİ ─────────
('Vakko', 'trendyol', NULL, 'musteri@vakko.com', '08503038383', 'https://www.trendyol.com/vakko-x-b7890', 'kesfedildi', 'instagram', 'Niche: lüks elbise + takım + eşarp + aksesuar + çanta · 1934 kuruluş, Türkiye''nin ikonik lüks moda markası · Trendyol + D2C + flagship mağazalar · Lüks segment → tek olumsuz yorum yüksek biletli müşteriyi kaybettirir · Hediye (düğün, özel gün, kurumsal) ağırlıklı = müşteri beklentisi maksimum · Marka kurucusu hikâyesi & prestij algısı yorum yanıt tonunu belirler → SatıcıPilot şablon yanıt lüks brand sesini korur'),
('Silk & Cashmere', 'trendyol', NULL, 'musteri@silkandcashmere.com', '08502991999', 'https://www.trendyol.com/silk-cashmere-x-b8901', 'kesfedildi', 'instagram', 'Niche: kaşmir kazak + ipekli eşarp + merino yün + lüks aksesuar · Türkiye''nin lider lüks tekstil markası, 50+ mağaza · Trendyol + HB + D2C + yurt dışı retail · 1.000-8.000 TL ürün aralığı → her yorum satın alma kararını doğrudan etkiler · Kumaş kalitesi & pilling şikayetleri premium segmentte marka imajına zarar verir → SatıcıPilot yorum izleme alarm sistemi kritik · Hediye & kurumsal segment yoğun'),

-- ── PREMİUM EVCİL HAYVAN — TUTKULU SAHİP KİTLESİ ───────────────
('Royal Canin Türkiye', 'hepsiburada', NULL, 'info@royalcanin.com.tr', NULL, 'https://www.hepsiburada.com/magaza/royal-canin', 'kesfedildi', 'website', 'Niche: ırk & yaşa özel kedi-köpek maması + veteriner diyetik ürünler · Mars Inc. iştiraki, premium evcil hayvan beslenmesi dünya lideri · Trendyol + HB + veteriner klinikler + petshop · Evcil hayvan sahipleri en detaylı yorumları yazan segment; ürün değişikliği & formül şikayetleri çok hassas → SatıcıPilot yorum izleme & hızlı yanıt marka güveni için kritik · Abonelik satın alma davranışı = sadık müşteri, olumsuz deneyim direkt kayıp'),

-- ── MEDİKAL & SAĞLIK TEKNOLOJİSİ — HASSAS YORUM, YÜKSEK RİSK ──
('Omron Türkiye', 'trendyol', NULL, 'info@omron-healthcare.com.tr', NULL, 'https://www.trendyol.com/omron-x-b9012', 'kesfedildi', 'website', 'Niche: tansiyon aleti + nebulizatör + glukoz ölçer + ağrı kesici tens · Japon medikal cihaz devi, Türkiye yetkili distribütörü · Trendyol + HB + eczane kanalı · Tıbbi cihaz yorumları ölçüm doğruluğu & sağlık sonucu odaklı → hatalı bilgi içeren yorum hukuki risk yaratır · SatıcıPilot yorum izleme & şablon yanıt medikal compliance için kritik · Yaşlı kullanıcı segmenti destek talepleri yoğun, teknik sorular ayrıntılı'),
('Beurer Türkiye', 'trendyol', NULL, 'info@beurer.com.tr', NULL, 'https://www.trendyol.com/beurer-x-b1230', 'kesfedildi', 'website', 'Niche: ısı yastığı + masaj aleti + tansiyon + termometre + lamba terapi · Alman wellness & sağlık cihazları markası, Türkiye yetkili distribütörü · Trendyol + HB + eczane · Geniş ürün yelpazesi = herbir kategoride farklı yorum tipi (ısı, titreşim, ölçüm hassasiyeti) · Kronik hastalık & yaşlı kullanıcı segmenti → yorum detaylı, beklenti yüksek · SatıcıPilot çok kategorili yorum yönetimi & şablon yanıt sağlık hassasiyetinde değer'),

-- ── VALİZ & SEYAHAT — HASAR İADESİ & SEZON PATLAMASI ───────────
('Samsonite Türkiye', 'trendyol', NULL, 'musteri@samsonite.com.tr', '08508113900', 'https://www.trendyol.com/samsonite-x-b2301', 'kesfedildi', 'website', 'Niche: hardshell valiz + kumaş valiz + iş çantası + sırt çantası + aksesuar · Global valiz markasının Türkiye yetkili kanalı · Trendyol + HB + D2C + AVM · Kargo hasarı (tekerleksiz, çizik, çatlak) iade oranı valiz kategorisinde en yükseklerden → SatıcıPilot iade kalıp analizi kargo firma bazlı sorun tespiti · Yaz tatili & yılbaşı sezonunda patlama → kampanya zamanlaması kritik · Premium segment → hasar yorumları diğer müşterileri direkt etkiler'),

-- ── BEBEK & ÇOCUK — EBEVEYN YORUMLARI DUYGUSAL & DETAYLI ────────
('Chicco Türkiye', 'trendyol', NULL, 'info@chicco.com.tr', '08503999292', 'https://www.trendyol.com/chicco-x-b3412', 'kesfedildi', 'website', 'Niche: bebek arabası + oto koltuğu + mama sandalyesi + oyuncak + banyo + beslenme · İtalyan bebek ürünleri markası, Türkiye yetkili distribütörü · Trendyol + HB + bebek mağazaları · Güvenlik kritik ürünler = ebeveyn yorumları en detaylı ve en duygusal yoğun segment · Montaj & kullanım soruları çok gelir → şablon yanıt destek yükünü azaltır · Büyük ürün iadesi (araba koltuğu) lojistik karmaşık → SatıcıPilot iade süreç takibi operasyonel zorunluluk'),

-- ── MODA SAAT — HEDİYE SEGMENTİ & PREMIUM YORUM ────────────────
('Fossil Türkiye', 'trendyol', NULL, 'musteri@fossil.com.tr', NULL, 'https://www.trendyol.com/fossil-x-b4523', 'kesfedildi', 'instagram', 'Niche: moda saat + akıllı saat + deri bileklik + gözlük + aksesuar · Amerikan moda aksesuar markası, Türkiye yetkili distribütörü · Trendyol + HB + kendi mağazalar + AVM · Doğum günü / mezuniyet / yıldönümü hediyesi ağırlıklı → müşteri beklentisi maksimum, hediye ambalaj şikayeti bile iade gerektirebilir · 1.500-5.000 TL ürün bandı → her olumsuz yorumun gelir etkisi büyük · SatıcıPilot yorum alarm + hızlı yanıt premium marka imajını korur')

;
