-- SatıcıPilot — Lead Round 14 (14 lead)
-- Odak: Yüksek potansiyel profil — Vol 13'ün devamı
-- Segmentler: Ev Dekor, Deri & Ayakkabı, Fast Fashion, Lisanslı Uluslararası,
-- Dermo Kozmetik, Çok Kategorili Spor, Küçük Ev Aletleri

INSERT INTO leads (shop_name, marketplace, contact_name, contact_email, contact_phone, store_url, status, source, notes) VALUES

-- ── EV DEKOR & TEKSTİL — HIZLA BÜYÜYEN ZANJIR ──────────────────
('English Home', 'trendyol', NULL, 'musteri@englishhome.com.tr', '08502031555', 'https://www.trendyol.com/english-home-x-b456', 'kesfedildi', 'instagram', 'Niche: ev tekstili + dekor + mutfak + banyosofra + sezon koleksiyonu · 200+ mağaza, Türkiye''nin hızlı büyüyen ev yaşam zinciri · Trendyol + HB + D2C · 8 haftada bir komple yeni koleksiyon → sürekli yeni SKU = açıklama güncelleme & tag optimizasyonu iş yükü çok yüksek · Hediye segmenti yoğun (özel gün, ev armağanı) → müşteri beklentisi yüksek, yorum detaylı · SatıcıPilot koleksiyon bazlı kampanya otomasyonu net değer'),
('Madame Coco', 'trendyol', NULL, 'musteri@madamecoco.com.tr', NULL, 'https://www.trendyol.com/madame-coco-x-b567', 'kesfedildi', 'instagram', 'Niche: nevresim + oda tekstili + mum + dekor aksesuar + soft furnishing · Online-native büyüyen Türk ev dekor markası · 80+ mağaza, Trendyol + HB + D2C · Instagram influencer kampanyaları → satış + yorum dalgası ani geliyor · Yeni ev & düğün hediyesi segmenti = müşteri beklentisi yüksek, yanıtsız yorum dönüşüm kaybettiriyor → SatıcıPilot yorum izleme & hızlı şablon yanıt öncelikli'),

-- ── DERİ & AYAKKABI — İADE BASKISI YÜKSEK SEGMENT ──────────────
('Greyder', 'trendyol', NULL, 'info@greyder.com.tr', '08504512525', 'https://www.trendyol.com/greyder-x-b678', 'kesfedildi', 'instagram', 'Niche: spor & casual sneaker + günlük ayakkabı + bot · Türkiye''nin önde gelen ayakkabı markalarından · Trendyol + HB + 50+ mağaza · Numara uyumsuzluğu iade oranı ayakkabı kategorisinde yapısal yüksek → SatıcıPilot iade kalıp analizi ile hangi modelde sorun olduğu net tespit edilir · Instagram''dan viral olan modellerde stok bitimi şikayeti yoğun → stok uyarısı otomasyonu değerli'),
('Derimod', 'trendyol', NULL, 'musteri@derimod.com.tr', '08503374763', 'https://www.trendyol.com/derimod-x-b789', 'kesfedildi', 'instagram', 'Niche: deri ayakkabı + çanta + kemer + cüzdan + deri aksesuar · 50+ mağaza, Trendyol + HB + D2C · Premium deri segmenti → kargo hasarı & deri kalite şikayetleri yorum tonunu belirler · Hediye (babalar günü, yılbaşı) döneminde bilet yüksek ürünlerde müşteri beklentisi kritik → SatıcıPilot yorum yanıt hızı brand itibarı korur · İndirim kampanyalarında büyük yorum dalgası'),

-- ── FAST FASHION — BÜYÜK HACİM, KÜÇÜK E-KOMERSİ EKİBİ ─────────
('Koton', 'trendyol', NULL, 'musteri@koton.com', '08504009040', 'https://www.trendyol.com/koton-x-b234', 'kesfedildi', 'instagram', 'Niche: kadın-erkek-çocuk fast fashion · 300+ Türkiye mağazası, 30+ ülke · Trendyol + HB + D2C · Sezon geçişi & Black Friday döneminde yorum + sipariş patlaması → manuel yorum yönetimi imkânsız hale geliyor · Geniş yaş & ürün segmenti = farklı yorum profilleri → SatıcıPilot kategorize & şablon yanıt özelliği yüksek verimlilik · Beden uyumsuzluğu iade oranı yapısal yüksek'),
('Mudo', 'trendyol', NULL, 'musteri@mudo.com.tr', '08504120333', 'https://www.trendyol.com/mudo-x-b345', 'kesfedildi', 'instagram', 'Niche: kadın & erkek lifestyle giyim + ev aksesuar + dekor · Çok kategorili Türk lifestyle markası, 50+ mağaza · Trendyol + HB + D2C · Giyim + ev kategorisini aynı anda yönetmek = farklı yorum tiplerini bir ekip takip ediyor → SatıcıPilot unified yorum paneli bu profil için çok değerli · Sezon koleksiyonu lansmanlarında kampanya & yorum yönetimi baskı yaratıyor'),
('W Collection', 'trendyol', NULL, 'info@wcollection.com.tr', NULL, 'https://www.trendyol.com/w-collection-x-b678', 'kesfedildi', 'instagram', 'Niche: kadın casual giyim + elbise + bluz + pantolon · Online-first büyüyen Türk kadın moda markası · Trendyol + HB + D2C · Sosyal medya driven büyüme → influencer kampanyası sonrası sipariş & yorum dalgası yönetilemiyor · Genç müşteri kitlesi hızlı yanıt bekler; yanıtsız yorum doğrudan sepet terk ettiriyor → SatıcıPilot yorum izleme + hızlı yanıt öncelik'),

-- ── LİSANSLI & ULUSLARARASI OPERATÖR — TÜRK EKİP, GLOBAL MARKA ─
('U.S. Polo Assn Türkiye', 'trendyol', NULL, 'musteri@uspoloassn.com.tr', '08504006233', 'https://www.trendyol.com/u-s-polo-assn-x-b567', 'kesfedildi', 'instagram', 'Niche: erkek & kadın casual polo + denim + sneaker + aksesuar · Faber Grup tarafından işletilen lisanslı marka · 100+ Türkiye mağazası · Trendyol + HB + D2C · Global marka bilinirliği → müşteri beklentisi yüksek, olumsuz yorum brand algısını zedeler · Lisanslı operatör = sınırlı ekip boyutu → SatıcıPilot otomasyon ihtiyacı net · Sezon kampanyaları (Efsane Günü, Black Friday) döneminde sipariş & yorum patlaması'),
('Tchibo Türkiye', 'trendyol', NULL, 'musteri@tchibo.com.tr', '08502010000', 'https://www.trendyol.com/tchibo-x-b789', 'kesfedildi', 'website', 'Niche: sezonsal giyim + mutfak aletleri + teknoloji aksesuarı + kahve & kapsül · Alman zincirinin Türkiye operasyonu · 8 haftada bir komple yeni ürün koleksiyonu (100+ SKU) → dünyanın en sık SKU yenileme ritmi · Trendyol + HB + D2C + fiziksel mağaza · Farklı kategorilerde (giyim, mutfak, tech) eş zamanlı yorum yönetimi tek ekiple çok ağır → SatıcıPilot çok kategorili yorum paneli bu profil için benchmark use-case'),

-- ── DERMO KOZMETİK — TEKNİK YORUM & ECZANE KANALINA GEÇİŞ ─────
('Avene Türkiye', 'trendyol', NULL, 'info@avene.com.tr', NULL, 'https://www.trendyol.com/avene-x-b12345', 'kesfedildi', 'website', 'Niche: hassas & atopik cilt termal su + nemlendirici + güneş koruma · Pierre Fabre Türkiye distribütörü · Trendyol + eczane kanalı + HB · Dermokozmetik yorumları teknik & klinik içerikli gelir (cilt reaksiyonu, allerji, doktor önerisi) → şablon yanıt hazırlanması uzman içerik gerektirir · SatıcıPilot şablon yanıt + yorum kategorize özelliği dermokozmetik için kritik uyum · Eczaneden e-ticaret kanalına geçiş = yorum hacmi hızla büyüyor'),
('Bioderma Türkiye', 'trendyol', NULL, 'info@bioderma.com.tr', NULL, 'https://www.trendyol.com/bioderma-x-b23456', 'kesfedildi', 'website', 'Niche: micellar su (Sensibio H2O) + cilt bakım + güneş + akne ürünleri · NAOS Group Türkiye distribütörü · Trendyol + HB + eczane zinciri · Sensibio H2O ikonik ürün = tek SKU''da yüzlerce yorum · Sahte ürün şüphesi yorumları marka itibarını zedeler → SatıcıPilot yorum izleme & hızlı yanıt marka koruması için kritik · Eczane kanalından e-ticarete kayış hızlanıyor'),

-- ── KÜÇÜK EV ALETLERİ — YÜKSEK SKU, TEKNİK YORUM ──────────────
('Fakir', 'trendyol', NULL, 'info@fakir.com.tr', '02165707071', 'https://www.trendyol.com/fakir-x-b456', 'kesfedildi', 'website', 'Niche: elektrikli kettle + blender + tost makinesi + ütü + süpürge · 1962 kuruluş, Türkiye''nin köklü küçük ev aletleri markalarından · Trendyol + HB + teknoloji perakendecileri · Teknik arıza & kullanım güçlüğü yorumları detaylı gelir → SatıcıPilot yorum kategorize & şablon yanıt teknik destek yükü azaltır · Garanti & servis iade süreci yoğun → iade takip modülü operasyonel zorunluluk'),

-- ── ÇOK KATEGORİLİ SPOR — FARKLI YORUM PROFİLİ ────────────────
('Decathlon Türkiye', 'trendyol', NULL, 'musteri@decathlon.com', '08504444455', 'https://www.trendyol.com/decathlon-x-b567', 'kesfedildi', 'website', 'Niche: bisiklet + kamp + yüzme + fitness + koşu + dağcılık + futbol ekipmanı · Fransız spor devi, Türkiye''nin en büyük spor ekipmanı perakendecilerinden · 30+ mağaza + Trendyol + D2C · 50+ spor branşında ürün = herbir kategoride farklı yorum tipi ve teknik soru → SatıcıPilot çok kategorili yorum yönetimi bu profil için benchmark · Teknik ürün soruları (boyut, uyumluluk, dayanıklılık) destek yükünü artırıyor · Kamp & outdoor sezonu (Mart-Temmuz) patlama'),
('Adl', 'trendyol', NULL, 'info@adl.com.tr', NULL, 'https://www.trendyol.com/adl-x-b678', 'kesfedildi', 'instagram', 'Niche: kadın & erkek casual giyim + basics + dış giyim · Trendyol''da aktif büyüyen Türk casual moda markası · Trendyol + HB + D2C · Online-native büyüme sürecinde yorum & iade yönetimi ekip kapasitesini aşmaya başlıyor → SatıcıPilot ile otomasyon tam zamanında · Influencer iş birlikleri + kampanya dönemlerinde yorum dalgası yönetilemiyor')

;
