"""
Returns — worker-generated report endpoint only.

List/read operations are handled by the dashboard directly via Supabase (RLS).
FastAPI's role here: expose pattern reports generated by Celery workers and
allow on-demand batch analysis trigger.
"""
from fastapi import APIRouter, Depends
from app.core.database import get_supabase_admin
from app.core.security import get_current_user
from app.workers.tasks.return_tasks import generate_seller_return_report

router = APIRouter()


@router.get("/report")
def get_return_report(seller_id: str = Depends(get_current_user)):
    """
    Return the latest pattern report generated by the nightly Celery worker.
    The report contains dominant return reasons per product and actionable recommendations.
    """
    db = get_supabase_admin()
    report = (
        db.table("return_reports")
        .select("*")
        .eq("seller_id", seller_id)
        .order("created_at", desc=True)
        .limit(1)
        .execute()
    )
    if not report.data:
        return {"message": "Henüz rapor yok. İlk analiz bir sonraki gece çalışacak veya /batch-analyze ile tetikleyebilirsin."}
    return report.data[0]


@router.post("/batch-analyze")
def enqueue_batch_analysis(seller_id: str = Depends(get_current_user)):
    """Enqueue a Celery task to regenerate the return pattern report for this seller."""
    generate_seller_return_report.delay(seller_id)
    return {"status": "queued"}
